/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    artists: Artist;
    releases: Release;
    tracks: Track;
    'value-splits': ValueSplit;
    'audio-media': AudioMedia;
    'analytics-verification-receipts': AnalyticsVerificationReceipt;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    artists: ArtistsSelect<false> | ArtistsSelect<true>;
    releases: ReleasesSelect<false> | ReleasesSelect<true>;
    tracks: TracksSelect<false> | TracksSelect<true>;
    'value-splits': ValueSplitsSelect<false> | ValueSplitsSelect<true>;
    'audio-media': AudioMediaSelect<false> | AudioMediaSelect<true>;
    'analytics-verification-receipts': AnalyticsVerificationReceiptsSelect<false> | AnalyticsVerificationReceiptsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'publishing-settings': PublishingSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'publishing-settings': PublishingSettingsSelect<false> | PublishingSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'heroEffects' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Small text above the title (e.g. "⚡ Artist Cooperative · Lightning Network ⚡")
     */
    preHeading?: string | null;
    /**
     * Each line of the hero title can have its own font, color, size, and animation
     */
    titleLines?:
      | {
          text: string;
          font?: ('bangers' | 'vt323' | 'blackHanSans') | null;
          color?: ('white' | 'red' | 'yellow' | 'acid' | 'outline-white' | 'outline-red') | null;
          size?: ('xl' | 'lg' | 'md' | 'sm') | null;
          animation?: ('none' | 'glitch1' | 'glitch2' | 'shake' | 'pulse-red' | 'flicker') | null;
          /**
           * Adds an offset red shadow duplicate behind this line with its own glitch animation
           */
          enableGhostLayer?: boolean | null;
          /**
           * Slight rotation for a hand-placed look (e.g. -2)
           */
          rotation?: number | null;
          id?: string | null;
        }[]
      | null;
    badge?: {
      enabled?: boolean | null;
      /**
       * e.g. "★ Music is Medicine ★"
       */
      text?: string | null;
    };
    /**
     * Supporting text below the title. Use {red}text{/red} and {yel}text{/yel} for colored spans.
     */
    tagline?: string | null;
    /**
     * Large diagonal decorative text behind the hero (e.g. "MPM")
     */
    ghostText?: string | null;
    enableOrnaments?: boolean | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | {
        media: number | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaBlock';
      }
    | ArchiveBlock
    | FormBlock
    | ArtistGridBlock
    | TickerBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles: ('admin' | 'publisher' | 'artist')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArtistGridBlock".
 */
export interface ArtistGridBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'artistGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TickerBlock".
 */
export interface TickerBlock {
  items?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower = faster scrolling
   */
  speed?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ticker';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists".
 */
export interface Artist {
  id: number;
  /**
   * Account that owns this artist profile
   */
  user?: (number | null) | User;
  name: string;
  slug: string;
  bio?: string | null;
  /**
   * Artist website URL
   */
  website?: string | null;
  socialLinks?:
    | {
        platform: 'nostr' | 'twitter' | 'mastodon' | 'instagram' | 'youtube' | 'bandcamp' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Artist profile image
   */
  image?: (number | null) | Media;
  /**
   * Default Lightning address for this artist (user@provider.com)
   */
  lightningAddress?: string | null;
  status?: ('active' | 'inactive') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases".
 */
export interface Release {
  id: number;
  title: string;
  slug: string;
  type: 'single' | 'album';
  /**
   * podcast:medium — determines feed type (music or video)
   */
  medium?: ('music' | 'video') | null;
  artist: number | Artist;
  releaseDate?: string | null;
  /**
   * Square cover art (3000x3000 recommended)
   */
  coverImage?: (number | null) | Media;
  /**
   * Wide banner image (3000x1000 recommended)
   */
  bannerImage?: (number | null) | Media;
  description?: string | null;
  /**
   * Contains explicit content
   */
  explicit?: boolean | null;
  genre?:
    | (
        | 'Alternative'
        | 'Americana/Folk'
        | 'Blues'
        | 'Childrens'
        | 'Christmas'
        | 'Classical'
        | 'Country'
        | 'Dance/Electronic'
        | 'Instrumental'
        | 'Jazz'
        | 'Other'
        | 'Pop'
        | 'R&B/Hip Hop'
        | 'Reggae'
        | 'Rock'
        | 'Soundtrack'
      )
    | null;
  /**
   * Up to 4 subgenre tags
   */
  subgenres?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * podcast:locked — prevent feed scraping by other platforms
   */
  feedLocked?: boolean | null;
  /**
   * e.g. Creative Commons BY 4.0
   */
  license?: string | null;
  /**
   * Universal Product Code (album-level)
   */
  upc?: string | null;
  /**
   * Recording location (Studio, City, etc.)
   */
  location?: string | null;
  /**
   * Nostr or social discussion URL
   */
  socialUrl?: string | null;
  /**
   * Payment / support links for the whole release. Tracks can override these individually.
   */
  fundingLinks?:
    | {
        /**
         * Sets the button label and icon
         */
        provider: 'cashapp' | 'venmo' | 'paypal' | 'buymeacoffee' | 'kofi' | 'lightning' | 'other';
        /**
         * Optional custom button text (defaults to the provider name)
         */
        label?: string | null;
        /**
         * Full link. e.g. Cash App https://cash.app/$handle · Venmo https://venmo.com/u/handle · PayPal https://paypal.me/handle · Lightning: an address like you@getalby.com
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Suggested sats per stream
   */
  suggestedSats?: number | null;
  /**
   * How this release appears and behaves as a channel on myradio.nathandale.com
   */
  myradio?: {
    /**
     * Small caps line above the title, e.g. "LOOKING STAR / FIRST SIGNAL OUT"
     */
    kicker?: string | null;
    /**
     * Desktop visual theme for this channel
     */
    theme?: ('catalog' | 'terrestrial' | 'nathan-archive' | 'wooden-revolt' | 'parade' | 'monochrome') | null;
    /**
     * Version of the shared release-theme schema this record’s theme fields conform to (src/schemas/release-theme.schema.json).
     */
    themeSchemaVersion?: number | null;
    /**
     * Increments whenever the published theme or its assets change. Drives cache invalidation, and invalidates any stored preview attestation or analytics receipt for this release.
     */
    themeRevision?: number | null;
    /**
     * Approved release-identity assets shared by full MYRADIO, the Signal Card, and social-card output. Never a generated imitation.
     */
    themeAssets?: {
      /**
       * Approved release background image.
       */
      backgroundImage?: (number | null) | Media;
      /**
       * Optional grain, paper, or signal texture.
       */
      textureImage?: (number | null) | Media;
      /**
       * Optional approved release mark.
       */
      markImage?: (number | null) | Media;
    };
    /**
     * Optional per-release color overrides of the selected preset. Leave any field blank to inherit that token from the preset. Validated against the shared release-theme schema.
     */
    themeTokens?: {
      /**
       * Hex color. Leave blank to inherit the preset.
       */
      chrome?: string | null;
      /**
       * Hex color. Leave blank to inherit the preset.
       */
      muted?: string | null;
      /**
       * Hex color. Leave blank to inherit the preset.
       */
      accent?: string | null;
      /**
       * Hex color. Leave blank to inherit the preset.
       */
      accentContrast?: string | null;
      /**
       * Hex color. Leave blank to inherit the preset.
       */
      beacon?: string | null;
      /**
       * Hex color. Leave blank to inherit the preset.
       */
      beaconGlow?: string | null;
      /**
       * Hex color. Leave blank to inherit the preset.
       */
      line?: string | null;
      /**
       * Hex color. Leave blank to inherit the preset.
       */
      panelStart?: string | null;
      /**
       * Hex color. Leave blank to inherit the preset.
       */
      panelEnd?: string | null;
      /**
       * Hex color. Leave blank to inherit the preset.
       */
      panelText?: string | null;
      /**
       * Hex color. Leave blank to inherit the preset.
       */
      panelMuted?: string | null;
      /**
       * Hex color. Leave blank to inherit the preset.
       */
      panelAlt?: string | null;
      /**
       * Hex color. Leave blank to inherit the preset.
       */
      panelActive?: string | null;
      /**
       * Hex color. Leave blank to inherit the preset.
       */
      actionBackground?: string | null;
      /**
       * Hex color. Leave blank to inherit the preset.
       */
      actionText?: string | null;
      /**
       * Hex color. Leave blank to inherit the preset.
       */
      popoverBackground?: string | null;
      /**
       * Hex color. Leave blank to inherit the preset.
       */
      popoverText?: string | null;
      /**
       * Hex color. Leave blank to inherit the preset.
       */
      popoverMuted?: string | null;
    };
    themeOptions?: {
      /**
       * Responsive artwork behavior.
       */
      artworkTreatment?: ('full' | 'crop' | 'framed') | null;
      /**
       * Installed type treatment only — no uploaded web fonts in v1. This starter allowlist should be confirmed/extended against the site theme’s actual installed treatments before the Signal Card ships.
       */
      typeTreatment?: ('default' | 'display' | 'mono') | null;
      surfaceTreatment?: ('solid' | 'gradient' | 'image' | 'image-gradient') | null;
      /**
       * Must honor reduced motion at the CSS level in MYRADIO; no arbitrary animation code.
       */
      motion?: ('none' | 'subtle') | null;
    };
    signalCard?: {
      layout?: ('standard' | 'broadcast' | 'archival' | 'minimal') | null;
      /**
       * Turn off only when the approved background is itself the identity.
       */
      showArtwork?: boolean | null;
    };
    socialCard?: {
      layout?: ('standard' | 'minimal') | null;
    };
    /**
     * Link back to the matching section on nathandale.com/heart
     */
    heartUrl?: string | null;
    /**
     * Channel order in the MY RADIO list — lower shows first. Ties fall back to release date.
     */
    order?: number | null;
    /**
     * Short URL alias, e.g. "mkp" → myradio.nathandale.com/playlist/mkp
     */
    token?: string | null;
    /**
     * Load this channel first when MY RADIO opens (only one should be checked)
     */
    isDefault?: boolean | null;
    /**
     * Enable the TERRESTRIAL → MY RADIO song handoff for this channel
     */
    terrestrialHandoff?: boolean | null;
  };
  /**
   * SHADOW story relationship and campaign controls for the Signal Card publishing system. Carried in the feed as <podcast:txt purpose="myradio:…">.
   */
  distribution?: {
    /**
     * Editorial framing. "Archive" for older/unreleased material being newly surfaced — never mark archive material as newly current.
     */
    releaseLane?: ('current' | 'archive' | 'catalog') | null;
    /**
     * Separate from the editing workflow: only "public" releases are intended to appear in the public publisher feed.
     */
    publicVisibility?: ('preview' | 'public' | 'archived') | null;
    /**
     * Canonical SHADOW story URL. Optional while drafting; required before "SHADOW ready".
     */
    shadowPostUrl?: string | null;
    /**
     * Ghost post slug for this release’s SHADOW story.
     */
    shadowPostSlug?: string | null;
    defaultShareTarget?: ('story' | 'song') | null;
    /**
     * Explicit authorization for public Signal Card embedding of this release.
     */
    embedEnabled?: boolean | null;
    /**
     * Stable campaign identifier for attribution/dashboard grouping. Immutable once the release reaches "scheduled" — enforced in the publish-validation hook, not just here.
     */
    campaignKey?: string | null;
    /**
     * Optional social title override. Falls back to the standard "{Track} — {Artist} | MYRADIO" title when blank.
     */
    shareTitle?: string | null;
    /**
     * Optional bounded social description override.
     */
    shareDescription?: string | null;
    analyticsSchemaVersion?: number | null;
  };
  /**
   * Set only by the "Run player preview" action (not yet available — depends on Workstream 1B). Invalidated automatically when theme, tracks, player version, or analytics schema version change afterward.
   */
  previewAttestation?: {
    attestedAt?: string | null;
    attestedBy?: (number | null) | User;
    /**
     * themeRevision value at the moment of attestation.
     */
    themeRevisionAt?: number | null;
    /**
     * Composite fingerprint of track IDs, durations, and audio identifiers at the moment of attestation.
     */
    trackFingerprintAt?: string | null;
    playerVersionAt?: string | null;
    schemaVersionAt?: number | null;
  };
  /**
   * Set only by the "Verify analytics" action (not yet available — depends on Workstream 1B/4). Every attempt, pass or fail, is permanently recorded in Analytics Verification Receipts; this is just the latest passing one.
   */
  analyticsVerification?: {
    latest?: (number | null) | AnalyticsVerificationReceipt;
    summary?: {
      verifiedAt?: string | null;
      verifiedBy?: (number | null) | User;
      environment?: string | null;
      schemaVersion?: number | null;
      playerVersion?: string | null;
      themeVersion?: number | null;
      sampleEventIds?:
        | {
            eventId?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  /**
   * Stable feed GUID for this release (auto-generated)
   */
  releaseGuid?: string | null;
  /**
   * Legacy two-value status. Kept as-is for backward compatibility with the existing feed routes — do not remove. `workflowState` below is the controlled, validated state for the Signal Card publishing system.
   */
  status?: ('draft' | 'published') | null;
  /**
   * Publisher/admin may advance most states; only admin may set "Scheduled" or "Published".
   */
  workflowState?:
    | (
        | 'draft'
        | 'media_ready'
        | 'player_previewed'
        | 'shadow_ready'
        | 'analytics_verified'
        | 'scheduled'
        | 'published'
        | 'archived'
      )
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Append-only record of every PostHog publishing-gate attempt (EO §15). Never edited or deleted.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-verification-receipts".
 */
export interface AnalyticsVerificationReceipt {
  id: number;
  release: number | Release;
  /**
   * Set when verification is track-scoped rather than release-wide.
   */
  track?: (number | null) | Track;
  attemptedAt?: string | null;
  attemptedBy?: (number | null) | User;
  environment: string;
  outcome: 'pass' | 'fail';
  schemaVersion?: number | null;
  playerVersion?: string | null;
  themeVersion?: number | null;
  sampleEventIds?:
    | {
        eventId?: string | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracks".
 */
export interface Track {
  id: number;
  title: string;
  slug: string;
  release: number | Release;
  /**
   * Position in the release tracklist
   */
  trackNumber: number;
  /**
   * Audio file upload (admin and publisher only)
   */
  audioFile?: (number | null) | AudioMedia;
  /**
   * External audio URL (if not using upload)
   */
  audioUrl?: string | null;
  /**
   * Audio MIME type
   */
  mimeType?: string | null;
  /**
   * File size in bytes
   */
  fileSize?: number | null;
  /**
   * Duration in seconds
   */
  duration?: number | null;
  /**
   * Video file URL (MP4/MOV/WebM)
   */
  videoUrl?: string | null;
  videoMimeType?: string | null;
  /**
   * Video file size in bytes
   */
  videoFileSize?: number | null;
  /**
   * WebVTT file URL for lyrics/captions
   */
  transcriptUrl?: string | null;
  /**
   * Year this song was released. Shown as a small © line in the MY RADIO info panel.
   */
  year?: number | null;
  /**
   * Songwriter(s), comma-separated. Shown on the back of the artwork in MY RADIO.
   */
  songwriters?: string | null;
  /**
   * Musicians and what they played — one per line. Shown on the back of the artwork.
   */
  personnel?: string | null;
  /**
   * Free text about this song. Shown on the back of the artwork; scrolls if long.
   */
  story?: string | null;
  /**
   * Turn OFF all payment links for this song, even if the release has them. Use this to monetize only some songs on a release.
   */
  hideFunding?: boolean | null;
  /**
   * Per-song payment links. When set, these override the release links for this track. (Ignored if “Hide funding” is on.)
   */
  fundingLinks?:
    | {
        /**
         * Sets the button label and icon
         */
        provider: 'cashapp' | 'venmo' | 'paypal' | 'buymeacoffee' | 'kofi' | 'lightning' | 'other';
        /**
         * Optional custom button text (defaults to the provider name)
         */
        label?: string | null;
        /**
         * Full link. e.g. Cash App https://cash.app/$handle · Venmo https://venmo.com/u/handle · PayPal https://paypal.me/handle · Lightning: an address like you@getalby.com
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Per-track artwork override (falls back to release cover)
   */
  artwork?: (number | null) | Media;
  description?: string | null;
  explicit?: boolean | null;
  /**
   * International Standard Recording Code
   */
  isrc?: string | null;
  /**
   * Per-track genre override (falls back to release genre)
   */
  genre?:
    | (
        | 'Alternative'
        | 'Americana/Folk'
        | 'Blues'
        | 'Childrens'
        | 'Christmas'
        | 'Classical'
        | 'Country'
        | 'Dance/Electronic'
        | 'Instrumental'
        | 'Jazz'
        | 'Other'
        | 'Pop'
        | 'R&B/Hip Hop'
        | 'Reggae'
        | 'Rock'
        | 'Soundtrack'
      )
    | null;
  subgenres?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Stable feed GUID (auto-generated)
   */
  guid?: string | null;
  /**
   * Immutable, human-safe public track ID (auto-generated from the GUID). Never derived from the title alone.
   */
  shareId?: string | null;
  /**
   * Optional bounded track-specific share copy.
   */
  shareExcerpt?: string | null;
  /**
   * Prevents accidental publication of unverified lyrics — checked by the publish-validation hook.
   */
  lyricsStatus?: ('missing' | 'draft' | 'verified' | 'not_applicable') | null;
  /**
   * Attestation that audio, artwork, lyrics, and promotional use are authorized.
   */
  rightsConfirmed?: boolean | null;
  rightsConfirmedAt?: string | null;
  rightsConfirmedBy?: (number | null) | User;
  /**
   * This track’s own data/audio readiness. Says nothing about public visibility — that is the parent Release’s decision alone.
   */
  trackReadiness?: ('draft' | 'media_ready' | 'preview_verified') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio-media".
 */
export interface AudioMedia {
  id: number;
  /**
   * Display name for this audio file
   */
  title?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "value-splits".
 */
export interface ValueSplit {
  id: number;
  /**
   * Attach to a release (for channel-level splits)
   */
  release?: (number | null) | Release;
  /**
   * Attach to a specific track (for per-track splits)
   */
  track?: (number | null) | Track;
  /**
   * Display name of the recipient
   */
  recipientName: string;
  /**
   * Payment method type
   */
  paymentType?: 'lightning' | null;
  /**
   * Lightning address (user@provider.com) or node pubkey
   */
  lightningAddress: string;
  /**
   * Split percentage (0–100)
   */
  percentage: number;
  /**
   * Role or notes (e.g. Artist, Producer, Songwriter)
   */
  role?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'artists';
        value: number | Artist;
      } | null)
    | ({
        relationTo: 'releases';
        value: number | Release;
      } | null)
    | ({
        relationTo: 'tracks';
        value: number | Track;
      } | null)
    | ({
        relationTo: 'value-splits';
        value: number | ValueSplit;
      } | null)
    | ({
        relationTo: 'audio-media';
        value: number | AudioMedia;
      } | null)
    | ({
        relationTo: 'analytics-verification-receipts';
        value: number | AnalyticsVerificationReceipt;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        preHeading?: T;
        titleLines?:
          | T
          | {
              text?: T;
              font?: T;
              color?: T;
              size?: T;
              animation?: T;
              enableGhostLayer?: T;
              rotation?: T;
              id?: T;
            };
        badge?:
          | T
          | {
              enabled?: T;
              text?: T;
            };
        tagline?: T;
        ghostText?: T;
        enableOrnaments?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        artistGrid?: T | ArtistGridBlockSelect<T>;
        ticker?: T | TickerBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArtistGridBlock_select".
 */
export interface ArtistGridBlockSelect<T extends boolean = true> {
  introContent?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TickerBlock_select".
 */
export interface TickerBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  speed?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists_select".
 */
export interface ArtistsSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  slug?: T;
  bio?: T;
  website?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  image?: T;
  lightningAddress?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases_select".
 */
export interface ReleasesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  medium?: T;
  artist?: T;
  releaseDate?: T;
  coverImage?: T;
  bannerImage?: T;
  description?: T;
  explicit?: T;
  genre?: T;
  subgenres?:
    | T
    | {
        name?: T;
        id?: T;
      };
  feedLocked?: T;
  license?: T;
  upc?: T;
  location?: T;
  socialUrl?: T;
  fundingLinks?:
    | T
    | {
        provider?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  suggestedSats?: T;
  myradio?:
    | T
    | {
        kicker?: T;
        theme?: T;
        themeSchemaVersion?: T;
        themeRevision?: T;
        themeAssets?:
          | T
          | {
              backgroundImage?: T;
              textureImage?: T;
              markImage?: T;
            };
        themeTokens?:
          | T
          | {
              chrome?: T;
              muted?: T;
              accent?: T;
              accentContrast?: T;
              beacon?: T;
              beaconGlow?: T;
              line?: T;
              panelStart?: T;
              panelEnd?: T;
              panelText?: T;
              panelMuted?: T;
              panelAlt?: T;
              panelActive?: T;
              actionBackground?: T;
              actionText?: T;
              popoverBackground?: T;
              popoverText?: T;
              popoverMuted?: T;
            };
        themeOptions?:
          | T
          | {
              artworkTreatment?: T;
              typeTreatment?: T;
              surfaceTreatment?: T;
              motion?: T;
            };
        signalCard?:
          | T
          | {
              layout?: T;
              showArtwork?: T;
            };
        socialCard?:
          | T
          | {
              layout?: T;
            };
        heartUrl?: T;
        order?: T;
        token?: T;
        isDefault?: T;
        terrestrialHandoff?: T;
      };
  distribution?:
    | T
    | {
        releaseLane?: T;
        publicVisibility?: T;
        shadowPostUrl?: T;
        shadowPostSlug?: T;
        defaultShareTarget?: T;
        embedEnabled?: T;
        campaignKey?: T;
        shareTitle?: T;
        shareDescription?: T;
        analyticsSchemaVersion?: T;
      };
  previewAttestation?:
    | T
    | {
        attestedAt?: T;
        attestedBy?: T;
        themeRevisionAt?: T;
        trackFingerprintAt?: T;
        playerVersionAt?: T;
        schemaVersionAt?: T;
      };
  analyticsVerification?:
    | T
    | {
        latest?: T;
        summary?:
          | T
          | {
              verifiedAt?: T;
              verifiedBy?: T;
              environment?: T;
              schemaVersion?: T;
              playerVersion?: T;
              themeVersion?: T;
              sampleEventIds?:
                | T
                | {
                    eventId?: T;
                    id?: T;
                  };
            };
      };
  releaseGuid?: T;
  status?: T;
  workflowState?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracks_select".
 */
export interface TracksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  release?: T;
  trackNumber?: T;
  audioFile?: T;
  audioUrl?: T;
  mimeType?: T;
  fileSize?: T;
  duration?: T;
  videoUrl?: T;
  videoMimeType?: T;
  videoFileSize?: T;
  transcriptUrl?: T;
  year?: T;
  songwriters?: T;
  personnel?: T;
  story?: T;
  hideFunding?: T;
  fundingLinks?:
    | T
    | {
        provider?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  artwork?: T;
  description?: T;
  explicit?: T;
  isrc?: T;
  genre?: T;
  subgenres?:
    | T
    | {
        name?: T;
        id?: T;
      };
  guid?: T;
  shareId?: T;
  shareExcerpt?: T;
  lyricsStatus?: T;
  rightsConfirmed?: T;
  rightsConfirmedAt?: T;
  rightsConfirmedBy?: T;
  trackReadiness?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "value-splits_select".
 */
export interface ValueSplitsSelect<T extends boolean = true> {
  release?: T;
  track?: T;
  recipientName?: T;
  paymentType?: T;
  lightningAddress?: T;
  percentage?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio-media_select".
 */
export interface AudioMediaSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-verification-receipts_select".
 */
export interface AnalyticsVerificationReceiptsSelect<T extends boolean = true> {
  release?: T;
  track?: T;
  attemptedAt?: T;
  attemptedBy?: T;
  environment?: T;
  outcome?: T;
  schemaVersion?: T;
  playerVersion?: T;
  themeVersion?: T;
  sampleEventIds?:
    | T
    | {
        eventId?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publishing-settings".
 */
export interface PublishingSetting {
  id: number;
  /**
   * Base URL for generated feeds (e.g. https://magicpillmusic.com)
   */
  baseFeedUrl?: string | null;
  /**
   * Default podcast/feed title
   */
  podcastTitle?: string | null;
  /**
   * Default podcast description
   */
  podcastDescription?: string | null;
  language?: string | null;
  /**
   * Default copyright string for feeds
   */
  defaultCopyright?: string | null;
  /**
   * Default iTunes/podcast category
   */
  defaultCategory?: string | null;
  defaultSubcategory?: string | null;
  /**
   * Feed owner name
   */
  ownerName?: string | null;
  /**
   * Feed owner email
   */
  ownerEmail?: string | null;
  publisherName?: string | null;
  publisherUrl?: string | null;
  /**
   * Default suggested sats per stream
   */
  defaultSuggestedSats?: number | null;
  /**
   * Default feed image / site logo
   */
  siteImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publishing-settings_select".
 */
export interface PublishingSettingsSelect<T extends boolean = true> {
  baseFeedUrl?: T;
  podcastTitle?: T;
  podcastDescription?: T;
  language?: T;
  defaultCopyright?: T;
  defaultCategory?: T;
  defaultSubcategory?: T;
  ownerName?: T;
  ownerEmail?: T;
  publisherName?: T;
  publisherUrl?: T;
  defaultSuggestedSats?: T;
  siteImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'releases';
          value: number | Release;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}